In [ ]:
#This nodebook contains basic numpy exercises

In [2]:
import numpy as np
from numpy import dtype

#creating 1d array using numpy
ar1_1d=np.array([10,20,30,40])
print(ar1_1d)
print(ar1_1d.dtype) # defines the data type
ar2_dtype=np.array([5.5,6.6,7.7,8.8],dtype=float)
print(ar2_dtype, ar2_dtype.dtype)

#vectorized operations example
listexample=[1,2,3,4]
nparr=np.array([1,2,3,4])
print(listexample*2) # it duplicates the list
print(nparr+2)
print(nparr*2)# multiplies each element



[10 20 30 40]
int64
[5.5 6.6 7.7 8.8] float64
[1, 2, 3, 4, 1, 2, 3, 4]
[3 4 5 6]
[2 4 6 8]


In [3]:
#creating arrays using numpy features
print("all zeros\n", np.zeros(4))
print("all ones\n",np.ones(4))
print("range of 0-10, step up by 4\n",np.arange(0,10,4))
print("linspace minval,maxval, number of vals\n",np.linspace(0,3,15))
print(" random 2X2 matrix\n",np.random.random((2,2)))
print(" 2D random 4X4 matrix in range of 1-10\n",np.random.randint(1,10,(4,4)))
print(" 3D random  matrix in range of 1-10\n",np.random.randint(1,10,(3,3,3)))


all zeros
 [0. 0. 0. 0.]
all ones
 [1. 1. 1. 1.]
range of 0-10, step up by 4
 [0 4 8]
linspace minval,maxval, number of vals
 [0.         0.21428571 0.42857143 0.64285714 0.85714286 1.07142857
 1.28571429 1.5        1.71428571 1.92857143 2.14285714 2.35714286
 2.57142857 2.78571429 3.        ]
 random 2X2 matrix
 [[0.34727723 0.02726324]
 [0.13749025 0.51388601]]
 2D random 4X4 matrix in range of 1-10
 [[1 8 6 8]
 [7 5 6 6]
 [7 4 8 5]
 [9 1 6 1]]
 3D random  matrix in range of 1-10
 [[[2 7 6]
  [8 1 6]
  [4 9 3]]

 [[3 6 1]
  [3 6 6]
  [3 4 5]]

 [[7 1 8]
  [3 2 7]
  [7 9 7]]]


In [5]:
#View and copy
#copy is new array
#view is the original array
CV_Arr=np.arange(5,20)
print(CV_Arr)
c_arr=CV_Arr.copy()
v_arr=CV_Arr.view()
CV_Arr[0]=1
print("After transpose\n",CV_Arr)
print("After transpose, copuy array\n",c_arr)
print("After transpose,view of array\n",v_arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After transpose
 [ 1  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After transpose, copuy array
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After transpose,view of array
 [ 1  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
#Array attributes
arrattr=np.array([[1,2,3],[5,6,7]])
print("array \n",arrattr)
print("array size\n",arrattr.size)# number of elements
print("array dtype \n",arrattr.dtype)
print("array shape \n",arrattr.shape)
print("array itemsize\n",arrattr.itemsize)# bytesize of each element
print("array numbe of dimension\n",arrattr.ndim)
print("array number of bytes\n",arrattr.nbytes)


array 
 [[1 2 3]
 [5 6 7]]
array size
 6
array dtype 
 int64
array shape 
 (2, 3)
array itemsize
 8
array numbe of dimension
 2
array number of bytes
 48


In [28]:
#basic math operations
math_oper=[1,2,3,4,5]
print(math_oper)
print(np.sum(math_oper))
print(np.add(math_oper,10))
print(np.subtract(math_oper,1))
print(np.multiply(math_oper,3))
print(np.power(math_oper,2))

#Trignometric Operations
theta=np.array([0,30,45,60,90])
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

#Logarithmic function
log_example=[1,10,100]
print(log_example)
print(np.log(log_example))
print(np.log2(log_example))
print(np.log10(log_example))


[1, 2, 3, 4, 5]
15
[11 12 13 14 15]
[0 1 2 3 4]
[ 3  6  9 12 15]
[ 1  4  9 16 25]
[ 0 30 45 60 90]
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
[1, 10, 100]
[0.         2.30258509 4.60517019]
[0.         3.32192809 6.64385619]
[0. 1. 2.]


In [38]:
#Reduce
reduce_example=[1,2,3,4,5,6]
print(reduce_example)
print(np.add.reduce(reduce_example))
#Accumulate
print(np.add.accumulate(reduce_example))
#aggregation
# mean,median ,min,max
example_aggregation=np.arange(1,10).reshape(3,3)
print(example_aggregation)
print(np.mean(example_aggregation))
print(np.median(example_aggregation))
print(np.min(example_aggregation))
print(np.max(example_aggregation))
print(np.std(example_aggregation))
print("min column",np.amin(example_aggregation,0))
print("min row", np.amin(example_aggregation,1))
print("max column",np.amax(example_aggregation,0))
print("max row", np.amax(example_aggregation,1))


[1, 2, 3, 4, 5, 6]
21
[ 1  3  6 10 15 21]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
5.0
1
9
2.581988897471611
min column [1 2 3]
min row [1 4 7]
max column [7 8 9]
max row [3 6 9]


In [42]:
#boolean mask
bool_example=np.random.randint(4,25,(3,3))
print(bool_example)
print(20<bool_example)
print(bool_example [bool_example>20])

[[20 13 19]
 [13 13 10]
 [16 20 23]]
[[False False False]
 [False False False]
 [False False  True]]
[23]


In [30]:
#Array Indexing
#1d array
arr_indx=np.array([1,2,3,4,5,6,7,8,9])
print("example 1d array",arr_indx)
print("Accesing array elements by array location 0 :",arr_indx[0])
print("Accesing array elements from end,using negative number -1 :",arr_indx[-1])
#Array slicing 1D [start:stop:step]
print("Slicing array [2:4]",arr_indx[2:4])
print("Slicing array [1:6:2]",arr_indx[1:6:2])
print("Slicing array [1: :3]",arr_indx[1: :3])
print("Slicing array [::-1]",arr_indx[::-1])
#slicing just projects the values 
print(arr_indx)



example 1d array [1 2 3 4 5 6 7 8 9]
Accesing array elements by array location 0 : 1
Accesing array elements from end,using negative number -1 : 9
Slicing array [2:4] [3 4]
Slicing array [1:6:2] [2 4 6]
Slicing array [1: :3] [2 5 8]
Slicing array [::-1] [9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [35]:
#two dimentional array
arr_ndimention=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("multi dimentional array",arr_ndimention)
print("[0,0] :",arr_ndimention[0,0],"\n[2,2] :",arr_ndimention[2,2])
print("[-1,-1] :",arr_ndimention[-1,-1],"\n[-3,-1] :",arr_ndimention[-3,-1])
#updating two dimentional array
arr_ndimention[2,2]=99
print("the new 2d array after updation \n", arr_ndimention)
#slicing 2d array
print("2d [:2,:2]\n",arr_ndimention[:2,:2])
print("2d[1:,1:]\n",arr_ndimention[1:,1:])
print("2d[::-1,::-1]\n",arr_ndimention[::-1,::-1])


multi dimentional array [[10 20 30]
 [40 50 60]
 [70 80 90]]
[0,0] : 10 
[2,2] : 90
[-1,-1] : 90 
[-3,-1] : 30
the new 2d array after updation 
 [[10 20 30]
 [40 50 60]
 [70 80 99]]
2d [:2,:2]
 [[10 20]
 [40 50]]
2d[1:,1:]
 [[50 60]
 [80 99]]
2d[::-1,::-1]
 [[99 80 70]
 [60 50 40]
 [30 20 10]]


In [40]:
#reshaping array
mat_3X2=np.array([[1,2],[3,4],[5,6]])
print("3X2 matrix\n", mat_3X2)

mat_2X3=mat_3X2.reshape(2,3)
print("2X3 matrix",mat_2X3 )
print("3X2 matrix",mat_3X2.reshape(3,2))
#create 1d array respae to 3X3
print(np.arange(1,30).reshape(3,3))



3X2 matrix
 [[1 2]
 [3 4]
 [5 6]]
2X3 matrix [[1 2 3]
 [4 5 6]]
3X2 matrix [[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [20]:
#concatenation and splitting
c1=np.ones((3,3))
c2=np.zeros((3,3))
c3=np.concatenate((c1,c2),axis=1)
print("concatenated matrix\n",c3)
#splittinh
s1,s2=np.split(c3,[2])
print("splitted matrix s1\n",s1)
print("splitted matrix s2\n",s2)
#vertical split
vup,vlow=np.vsplit(c3,[1])
print("vup \n",vup)
print("vlow \n",vlow)
#horizontal split
hleft,hright=np.hsplit(c3,[1])
print("hleft \n",hleft)
print("hright \n",hright)


concatenated matrix
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
splitted matrix s1
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
splitted matrix s2
 [[1. 1. 1. 0. 0. 0.]]
vup 
 [[1. 1. 1. 0. 0. 0.]]
vlow 
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
hleft 
 [[1.]
 [1.]
 [1.]]
hright 
 [[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
